language: go

os:
  - linux
  - osx
  - windows

env:
  - GO111MODULE=on CGO_ENABLED=0

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - tip

script:
    - go test -v -cover ./...
    - curl -sfL https://git.io/goreleaser | sh -s -- check # check goreleaser config for deprecations

deploy:
- provider: script
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
    go: 1.14.x
